/* =========================================================
   OUTBASE outbaseLifeV210.js
   UI v210: 安定版シェル + 散歩結果画面
   - lifeOSBase / walkUsability / walkResult を読まない
   - 1ファイル短縮で Unexpected end of input を回避
========================================================= */
(function(){
  'use strict';
  const ROOT='outbaseLifeOSV210', STYLE='outbaseLifeV210Style', WALK='outbaseWalkUseV210', RESULT='outbaseWalkResultV210';
  const PAGES={record:'outbaseRecordPageV210',calendar:'outbaseCalendarPageV210',project:'outbaseProjectPageV210',assets:'outbaseAssetsPageV210',result:RESULT};
  let route='home', rec=null, chunks=[];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function ready(){document.body.classList.add('outbase-life-ready');}
  function page(id){return document.getElementById(id);}
  function isActiveWalk(){try{return typeof currentSession!=='undefined'&&currentSession&&currentSession.status===(window.EVENT_STATUS?EVENT_STATUS.ACTIVE:'active');}catch(e){return false;}}
  function addStyle(){if(page(STYLE))return;let s=document.createElement('style');s.id=STYLE;s.textContent=`
    :root{--obg:#1f6f3a;--obd:#123d25;--obs:#edf6ee;--obt:#243127;--obm:#6b766c;--obl:#e5ebe4;}
    #homePage,.life210-page,#${RESULT}{background:linear-gradient(180deg,#f4f8f2 0%,#fbfaf5 100%);padding:14px 14px 104px;}
    .life210-wrap{display:flex;flex-direction:column;gap:14px}.life210-card{background:#fff;border:1px solid rgba(31,111,58,.08);border-radius:24px;padding:16px;box-shadow:0 10px 24px rgba(20,81,45,.08);color:var(--obt)}
    .life210-hero{background:linear-gradient(135deg,#1f6f3a,#4f8f5b);color:#fff;min-height:132px}.life210-k{font-size:12px;letter-spacing:.08em;opacity:.9}.life210-title{font-size:24px;font-weight:900;line-height:1.25}.life210-sub{font-size:13px;line-height:1.55;margin-top:8px;max-width:82%}
    .life210-grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.life210-grid3,.result210-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.life210-grid2,.walk210-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}
    .life210-btn,.walk210-btn,.result210-btn{border:1px solid var(--obl);border-radius:18px;background:#fff;color:var(--obd);font-weight:900;min-height:64px;padding:10px}.life210-btn span,.walk210-btn span{display:block;font-size:24px}.life210-primary,.walk210-voice{background:linear-gradient(180deg,var(--obg),var(--obd))!important;color:#fff!important;border:0!important}.walk210-end{background:#c62828!important;color:#fff!important;border:0!important}
    .life210-mini,.result210-mini{border:1px solid var(--obl);border-radius:18px;padding:12px;background:#fff;min-height:78px}.life210-label,.result210-label{font-size:12px;color:var(--obm)}.life210-value,.result210-value{font-size:19px;font-weight:900;line-height:1.3}.life210-note,.walk210-note,.result210-note{font-size:13px;color:var(--obm);line-height:1.5}
    .life210-nav{position:fixed;left:50%;transform:translateX(-50%);bottom:10px;width:min(680px,calc(100vw - 20px));display:grid;grid-template-columns:repeat(5,1fr);gap:2px;background:rgba(255,255,255,.96);border:1px solid rgba(31,111,58,.1);border-radius:22px;box-shadow:0 10px 22px rgba(20,81,45,.12);padding:8px;z-index:50}.life210-nav button{border:0;background:transparent;color:var(--obm);font-size:11px;font-weight:900;min-height:48px}.life210-nav button.on{color:var(--obd)}.life210-nav span{display:block;font-size:20px}
    #walkPage{background:linear-gradient(180deg,#f4f8f2 0%,#fbfaf5 100%);padding:14px 14px 104px}#walkPage>.card{border-radius:24px;box-shadow:0 10px 24px rgba(20,81,45,.08)}#walkPage .timer{font-size:44px;font-weight:900;text-align:center}.walk210-hide{display:none!important}.walk210-card{display:flex;flex-direction:column;gap:12px}.walk210-detail{border:1px solid var(--obl);border-radius:18px;padding:10px}.walk210-detail summary{font-weight:900;color:var(--obd)}.walk210-status{font-size:12px;color:var(--obm);min-height:18px}.result210-actions{display:flex;flex-direction:column;gap:10px}.result210-primary{background:linear-gradient(180deg,var(--obg),var(--obd));color:#fff;border:0}
    @media(max-width:520px){.life210-grid3,.result210-grid{grid-template-columns:repeat(3,1fr)}.life210-title{font-size:23px}.life210-card{padding:15px}.walk210-grid{gap:8px}}
  `;document.head.appendChild(s);}
  function ensure(id){let p=page(id);if(p)return p;p=document.createElement('div');p.id=id;p.className='page hidden life210-page';document.body.insertBefore(p,document.body.querySelector('script')||null);return p;}
  function hideAll(){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));}
  function nav(a){return `<nav class="life210-nav">${[['home','🏠','ホーム'],['record','📝','記録'],['calendar','📅','予定'],['project','🗂️','PJ'],['assets','📁','素材']].map(x=>`<button class="${a===x[0]?'on':''}" onclick="showOutbaseLifePageV210('${x[0]}')"><span>${x[1]}</span>${x[2]}</button>`).join('')}</nav>`;}
  async function allStore(n){try{return typeof getOutbaseStoreAll==='function'?await getOutbaseStoreAll(n):[]}catch(e){return[]}}
  async function records(){try{return typeof getRecords==='function'?await getRecords():[]}catch(e){return[]}}
  async function homeHtml(){let rs=await records(), inbox=await allStore('inbox_items');let latest=rs.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0))[0];let cnt=inbox.filter(x=>!['linked','deleted','done'].includes(x.status)).length;return `<div id="${ROOT}" class="life210-wrap"><section class="life210-card life210-hero"><div class="life210-k">OUTBASE LIFE OS</div><div class="life210-title">今日を整理して、<br>大事なことだけ知らせる。</div><div class="life210-sub">家族・ペット・予定・記録・素材・思い出をつなぐ入口。</div></section><section class="life210-card"><b>🌿 チャッピー：次回キャンプを確認できます</b><div class="life210-note">天気・買い物・ギア・当日メモをPJ側にまとめます。</div></section><section class="life210-card"><b>すぐ使う</b><div class="life210-grid4" style="margin-top:10px"><button class="life210-btn" onclick="startWalk&&startWalk()"><span>🐕</span>コタ散歩</button><button class="life210-btn" onclick="showOutbaseLifePageV210('record')"><span>📝</span>記録</button><button class="life210-btn" onclick="showOutbaseLifePageV210('calendar')"><span>📅</span>予定</button><button class="life210-btn" onclick="showOutbaseLifePageV210('assets')"><span>📁</span>素材</button></div></section><section class="life210-card"><b>提案・注意</b><div class="life210-grid3" style="margin-top:10px"><div class="life210-mini"><div class="life210-label">未整理</div><div class="life210-value">${cnt}件</div><div class="life210-note">多い時だけ整理提案</div></div><div class="life210-mini"><div class="life210-label">次回キャンプ</div><div class="life210-value">赤城山</div><div class="life210-note">準備はPJへ集約</div></div><div class="life210-mini"><div class="life210-label">直近</div><div class="life210-value">${esc(latest?.title||'記録なし')}</div><div class="life210-note">${esc(latest?.date||'')}</div></div></div></section>${nav('home')}</div>`;}
  async function showLife(k){addStyle();route=k;if(isActiveWalk()&&k==='home'){route='walk';showOnly('walkPage');applyWalk();return;}hideAll();let p=k==='home'?page('homePage'):ensure(PAGES[k]);if(k==='home')p.innerHTML=await homeHtml();else p.innerHTML=lifePage(k);p.classList.remove('hidden');ready();scrollTo(0,0);}
  function lifePage(k){let data={record:['RECORD','写真・音声・メモを迷わず残す。','＋ 記録入力を開く','showAssetCapturePage&&showAssetCapturePage()'],calendar:['CALENDAR','予定から準備と注意につなげる。','コタ散歩 / 次回キャンプ / 記念日 / 車検',''],project:['PROJECT','予定を準備・記録・レビューへ。','キャンプPJを開く/作る','openOutbaseCampPrep&&openOutbaseCampPrep()'],assets:['ASSETS','素材を確認して思い出と記録につなげる。','素材一覧を開く','showAssetInboxPage&&showAssetInboxPage()']}[k];return `<div class="life210-wrap"><section class="life210-card life210-hero"><div class="life210-k">${data[0]}</div><div class="life210-title">${data[1]}</div></section><section class="life210-card"><button class="life210-btn life210-primary" onclick="${data[3]||'return false'}">${data[2]}</button></section>${nav(k)}</div>`;}
  function showOnly(id){hideAll();let p=page(id);if(p)p.classList.remove('hidden');if(id!=='homePage'){let h=page('homePage');if(h)h.classList.add('hidden');}}
  function applyWalk(){addStyle();let w=page('walkPage');if(!w)return;route='walk';showOnly('walkPage');let first=w.querySelector(':scope>.card');if(first){first.classList.add('walk210-hero');let h=first.querySelector('h1');if(h&&!h.textContent.includes('🐕'))h.innerHTML='🐕 散歩中';}
    w.querySelectorAll(':scope>.card').forEach(c=>{if(c.id===WALK)return;if(c.querySelector('#titleInput,#photoInput,#audioInfo,#noteInput')||c.id==='walkC2Panel'||c.id==='walkQuickPanel')c.classList.add('walk210-hide');});
    let card=page(WALK);if(!card){card=document.createElement('div');card.id=WALK;card.className='card walk210-card';card.innerHTML=`<div><b style="font-size:22px">散歩で使うものだけ</b><span style="float:right" class="life210-note">現地用</span><div class="walk210-note">うんち/おしっこは必要な時だけ詳細から記録。</div></div><div class="walk210-grid"><button class="walk210-btn" data-a="photo"><span>📷</span>写真</button><button class="walk210-btn walk210-voice" data-a="voice"><span>🎤</span>長押し音声</button><button class="walk210-btn" data-a="friend"><span>🐶</span>犬友</button><button class="walk210-btn" data-a="spot"><span>📍</span>スポット</button></div><button class="walk210-btn walk210-end" data-a="finish"><span>■</span>散歩終了</button><details class="walk210-detail"><summary>詳しい記録を開く</summary><div class="walk210-grid" style="margin-top:10px"><button class="walk210-btn" data-a="poop">💩 うんち</button><button class="walk210-btn" data-a="pee">💧 おしっこ</button><button class="walk210-btn" data-a="rest">休憩</button><button class="walk210-btn" data-a="memo">メモ</button></div></details><div id="walk210Status" class="walk210-status">音声は長押し、離すと保存。</div>`;bindWalk(card);} if(first&&first.nextSibling!==card)first.insertAdjacentElement('afterend',card);}
  function bindWalk(c){c.addEventListener('click',async e=>{let b=e.target.closest('[data-a]');if(!b)return;let a=b.dataset.a;if(a==='photo'){let p=page('photoInput');if(p)p.click();} if(a==='friend')await addEvt('friend_dog','🐶 犬友達'); if(a==='spot')await addEvt('spot','📍 スポット'); if(a==='poop')await addEvt('poop','💩 うんち','うんち'); if(a==='pee')await addEvt('pee','💧 おしっこ','おしっこ'); if(a==='rest')await addEvt('rest','休憩','休憩'); if(a==='memo'){let t=prompt('散歩メモ','');if(t&&typeof saveAssetM0Memo==='function')saveAssetM0Memo(t,{context:{targetType:'walk'}});} if(a==='finish')finishWalk&&finishWalk();});let v=c.querySelector('[data-a="voice"]');if(v){v.onpointerdown=e=>{e.preventDefault();startVoice();};v.onpointerup=e=>{e.preventDefault();stopVoice();};v.onpointercancel=stopVoice;v.oncontextmenu=e=>e.preventDefault();}}
  async function addEvt(t,l,n){if(typeof addWalkC2Event==='function')await addWalkC2Event(t,l,n);}
  async function startVoice(){if(rec)return;try{let st=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(st);chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.start();setStatus('録音中。離すと保存します。');}catch(e){setStatus('音声メモを開始できません');}}
  async function stopVoice(){if(!rec)return;let r=rec;rec=null;r.onstop=async()=>{let blob=new Blob(chunks,{type:r.mimeType||'audio/webm'});let data=await blobToData(blob);if(typeof audioRecords!=='undefined')audioRecords.push({id:createId(),name:'walk_audio_'+Date.now()+'.webm',type:blob.type,data,time:new Date().toLocaleString(),created_at:new Date().toISOString()});if(typeof saveWalkActiveSession==='function')saveWalkActiveSession('audio');setStatus('音声メモを保存しました');r.stream.getTracks().forEach(x=>x.stop());};r.stop();}
  function blobToData(b){return new Promise((res,rej)=>{let fr=new FileReader();fr.onload=e=>res(e.target.result);fr.onerror=rej;fr.readAsDataURL(b);});} function setStatus(t){let e=page('walk210Status');if(e)e.textContent=t;}
  function patchStart(){if(typeof startWalk==='function'&&!startWalk.__v210){let o=startWalk;window.startWalk=function(){let r=o.apply(this,arguments);setTimeout(applyWalk,100);setTimeout(applyWalk,500);return r};window.startWalk.__v210=true;}if(typeof restoreWalkSession==='function'&&!restoreWalkSession.__v210){let o=restoreWalkSession;window.restoreWalkSession=function(x){let r=o.apply(this,arguments);setTimeout(applyWalk,120);return r};window.restoreWalkSession.__v210=true;}}
  function patchFinish(){if(typeof finishWalk!=='function'||finishWalk.__v210)return;window.finishWalk=function(){if(!confirm('散歩を終了して保存しますか？'))return;finishResult();};window.finishWalk.__v210=true;}
  async function finishResult(){try{if(typeof updateWalkTimer==='function')updateWalkTimer();if(typeof timerInterval!=='undefined'&&timerInterval)clearInterval(timerInterval);if(typeof stopAutoSave==='function')stopAutoSave();if(typeof gpsWatcher!=='undefined'&&gpsWatcher)clearInterval(gpsWatcher);let done=async gps=>{endGps=gps||'未取得';if(typeof addGpsHistory==='function')addGpsHistory('end',endGps);distanceKm=typeof calcTrackDistance==='function'?calcTrackDistance(gpsHistory):'0.00km';let wt=formatTime(seconds||0),avg=typeof calcAverageSpeed==='function'?calcAverageSpeed(distanceKm,wt):'0.00km/h';currentSession.endTime=new Date().toLocaleString();currentSession.status=EVENT_STATUS.CLOSED;let recd={id:createId(),title:'散歩記録',tags:[],recordType:'walk',session:currentSession,date:new Date().toLocaleString(),walk:{time:wt,distanceKm:distanceKm,avgSpeed:avg},gps:{start:startGps,end:endGps,history:gpsHistory},photos:photos,audio:audioRecords,notes:notes,summary:{photoCount:photos.length,audioCount:audioRecords.length,noteCount:notes.length,gpsPointCount:gpsHistory.length,validGpsPointCount:typeof getValidGpsCount==='function'?getValidGpsCount(gpsHistory):gpsHistory.length}};await saveRecord(recd);if(currentSession?.id&&typeof deleteActiveSession==='function')await deleteActiveSession(currentSession.id);if(typeof clearAppState==='function')clearAppState();showResult(recd);}; if(typeof getGps==='function')getGps(done);else done('未取得');}catch(e){console.error(e);alert('散歩終了に失敗しました');}}
  function showResult(r){addStyle();let p=ensure(RESULT);p.className='page';p.innerHTML=`<section class="life210-card life210-hero"><div class="life210-k">WALK RESULT</div><div class="life210-title">コタ散歩を保存しました</div><div class="life210-sub">散歩結果はここ、散歩履歴、詳細から確認できます。</div></section><section class="life210-card result210-grid"><div class="result210-mini"><div class="result210-label">時間</div><div class="result210-value">${esc(r.walk.time)}</div></div><div class="result210-mini"><div class="result210-label">距離</div><div class="result210-value">${esc(r.walk.distanceKm)}</div></div><div class="result210-mini"><div class="result210-label">GPS</div><div class="result210-value">${r.summary.validGpsPointCount}件</div></div></section><section class="life210-card result210-actions"><button class="result210-btn result210-primary" onclick="showDetail&&showDetail('${esc(r.id)}')">詳細を見る</button><button class="result210-btn" onclick="showWalkHistoryPage&&showWalkHistoryPage()">散歩履歴を開く</button><button class="result210-btn" onclick="showOutbaseLifePageV210('home')">ホームへ戻る</button></section>`;hideAll();p.classList.remove('hidden');route='result';scrollTo(0,0);}
  function patchPage(){if(typeof showPage==='function'&&!showPage.__v210){let o=showPage;window.showPage=function(id){if(id==='homePage'){showLife('home');return;}let r=o.apply(this,arguments);if(id==='walkPage')setTimeout(applyWalk,80);return r};window.showPage.__v210=true;}}
  function setup(){addStyle();Object.values(PAGES).forEach(ensure);patchPage();patchStart();patchFinish();if(isActiveWalk()||!page('walkPage')?.classList.contains('hidden'))applyWalk();else showLife('home');ready();}
  window.showOutbaseLifePageV210=showLife;window.showOutbaseLifePageV208=showLife;window.showOutbaseWalkResultV210=showResult;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();window.addEventListener('load',()=>setTimeout(setup,250));setInterval(()=>{patchStart();patchFinish();},1500);
})();
