
(()=> {
  'use strict';
  const VERSION='REBUILD14_BACK_MAP_SAFE';
  const KEY='outbase_rebuild14_state';
  const app=document.getElementById('app');
  const clone=o=>JSON.parse(JSON.stringify(o));
  const pad=n=>String(n).padStart(2,'0');
  const today=()=>new Date().toISOString().slice(0,10);
  const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  const fmt=s=>s?`${Number(s.slice(5,7))}/${Number(s.slice(8,10))}`:'未定';
  const nowTime=()=>new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=p=>p+'_'+Math.random().toString(36).slice(2,9);
  const seed={
    route:'home', currentMonth:'2026-07', selectedDate:'2026-07-08',
    page:{record:'home',prep:'home',memory:'home'}, query:'千葉 キャンプ場',
    plan:{title:'スノーピーク赤城山CF',type:'キャンプ',start:'2026-07-07',end:'2026-07-08',place:'スノーピーク赤城山キャンプフィールド',checkin:'13:00'},
    camp:{active:true,startedAt:'2026-07-08T14:12:00+09:00',endedAt:null},
    activeMode:'',
    events:[{id:'e1',title:'キャンプ',type:'camp',start:'2026-07-07',end:'2026-07-08'},{id:'e2',title:'スノーピーク赤城山CF',type:'camp',start:'2026-07-18',end:'2026-07-20'}],
    gear:[{id:'g1',name:'リビングシェル アイボリー',cat:'幕体',box:'home',qty:1,status:'home'},{id:'g2',name:'アメニティドームM アイボリー',cat:'幕体',box:'home',qty:1,status:'home'},{id:'g3',name:'スキレット大',cat:'料理',box:'home',qty:1,status:'home'},{id:'g4',name:'ドッグオフトン',cat:'ペット',box:'home',qty:1,status:'home'}],
    shopping:[{id:'s1',name:'ブラックタイガー',qty:'1パック',done:false},{id:'s2',name:'にんにく',qty:'1個',done:false},{id:'s3',name:'ピザ用チーズ',qty:'1袋',done:false},{id:'s4',name:'氷',qty:'1袋',done:false}],
    meals:[{id:'m1',name:'ガーリックシュリンプ',slot:'夜',ingredients:['エビ','にんにく','バター','レモン']},{id:'m2',name:'ピザ',slot:'夜',ingredients:['ピザ生地','チーズ','ソース']}],
    weather:[{id:'w1',label:'設営時の雨',done:false},{id:'w2',label:'風速',done:false},{id:'w3',label:'コタの暑さ',done:false}],
    records:[{id:'r1',kind:'開始',title:'自宅出発',time:'14:12',text:'キャンプ開始'},{id:'r2',kind:'終了',title:'コタ散歩終了',time:'14:13',text:'散歩記録'}],
    pins:[{id:'p1',name:'コンビニ候補',kind:'寄り道',time:'14:20',lat:null,lng:null},{id:'p2',name:'サイト前',kind:'場所',time:'15:10',lat:null,lng:null}],
    gps:{points:3760,gaps:51,distance:12.4}, routePlans:[], toast:'', undo:null, drawer:null, lastActionAt:0
  };
  let state=load();
  let holdTimer=null;
  function load(){try{const raw=localStorage.getItem(KEY);if(raw)return merge(clone(seed),JSON.parse(raw))}catch(e){}return clone(seed)}
  function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))a[k]=merge(a[k]||{},b[k]);else a[k]=b[k]}return a}
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function canAct(){const n=Date.now(); if(n-state.lastActionAt<650)return false; state.lastActionAt=n; return true}
  function toast(t){state.toast=t;save();render(false);setTimeout(()=>{state.toast='';save();render(false)},1300)}
  function undo(t,fn){state.undo={text:t,fn};save();render(false);setTimeout(()=>{if(state.undo&&state.undo.text===t){state.undo=null;save();render(false)}},10000)}
  function currentStatus(){return state.camp.active?'キャンプ中':'未開始'}
  function modeText(){return state.activeMode||'なし'}
  function nowText(){return state.camp.active?`キャンプ中 / いま：${modeText()}`:'まだ始めていない'}
  function top(){return `<div class="top"><div class="topRow"><button class="brand" data-go="home"><span class="logo">OB</span><span><b>OUTBASE</b><small>field system</small></span></button><button class="plan" data-go="home"><i class="dot"></i><span><b>${esc(state.plan.title)}</b><small>${fmt(state.plan.start)}〜${fmt(state.plan.end)} / ${esc(nowText())}</small></span></button></div><div class="chips"><span class="on">${esc(currentStatus())}</span><span>いま：${esc(modeText())}</span><span>記録は続く</span></div></div>`}
  function nav(){const items=[['home','⌂','ホーム'],['calendar','▦','予定'],['prep','◫','準備'],['record','＋','記録'],['memory','○','思い出']];return `<nav class="bottomNav">${items.map(([r,i,l])=>`<button class="${state.route===r?'active':''}" data-go="${r}"><b>${i}</b>${l}</button>`).join('')}</nav>`}
  function shell(html){return `<div class="shell">${top()}<main class="main">${html}</main></div>${drawer()}${state.toast?`<div class="toast">${esc(state.toast)}</div>`:''}${state.undo?`<div class="undo"><span>${esc(state.undo.text)}</span><button data-act="undo">取り消す</button></div>`:''}${nav()}`}
  function hero(label,title,body,badge='今'){return `<section class="hero"><div class="heroMeta"><span>${esc(label)}</span><span>OUTBASE</span></div><h1>${esc(title)}</h1><p>${esc(body)}</p><div class="now"><span><b>${esc(nowText())}</b><small>キャンプは出発から帰宅まで</small></span><i>${esc(badge)}</i></div></section>`}
  function back(label){return `<div class="back"><button data-back>← ${esc(label)}</button></div>`}
  function titleBox(t,s){return `<section class="title"><b>${esc(t)}</b><small>${esc(s)}</small></section>`}
  function mapEmbed(q){return `<section class="mapBox"><iframe loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://maps.google.com/maps?q=${encodeURIComponent(q)}&z=13&output=embed"></iframe></section>`}
  function home(){return shell(`<section class="page">${hero('HOME','今日は何をする？','キャンプ、散歩、準備、思い出から選ぶ。')}<section class="panel"><div class="panelHead"><b>まず選ぶ</b><small>主役の行動だけを置く</small></div><div class="grid4"><button class="card" data-record-page="camp"><b>キャンプに行く</b><small>出発・記録・帰宅</small></button><button class="card" data-record-page="kota"><b>コタ散歩する</b><small>出発・ピン・写真・帰宅</small></button><button class="card" data-go="prep"><b>準備する</b><small>買うもの・持ち物・ルート</small></button><button class="card" data-go="memory"><b>思い出を見る</b><small>履歴と写真を見返す</small></button></div></section><section class="mini"><button data-prep-page="gear">ギア</button><button data-go="discover">探す</button><button data-go="calendar">予定</button></section></section>`)}
  function calendar(){const [y,m]=state.currentMonth.split('-').map(Number),first=new Date(y,m-1,1),start=new Date(first);start.setDate(1-start.getDay());const cells=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);cells.push({date:iso(d),inMonth:d.getMonth()===m-1})}return shell(`<section class="page"><section class="calHead"><button data-act="prevMonth">‹</button><div class="calTitle"><b>${y}.${pad(m)}</b><small>日付枠を2回タップで追加</small></div><button data-act="nextMonth">›</button><button data-act="today">今日</button></section><div class="week">${['日','月','火','水','木','金','土'].map(w=>`<span>${w}</span>`).join('')}</div><div class="days">${cells.map(dayCell).join('')}</div><section class="info">連続予定はバーでつながる。通常のコタ散歩は予定に入れない。</section><button class="btn main" data-act="addEvent"><b>予定を足す</b><small>${fmt(state.selectedDate)}</small></button></section>`)}
  function dayEvents(date){return state.events.filter(e=>(e.start||date)<=date&&date<=(e.end||e.start||date)).slice(0,2)}
  function barClass(e,d){if(e.start===e.end)return 'single'; if(d===e.start)return 'start'; if(d===e.end)return 'end'; return 'mid'}
  function dayCell(c){const ev=dayEvents(c.date);return `<button class="day ${c.inMonth?'':'out'} ${c.date===today()?'today':''} ${c.date===state.selectedDate?'selected':''}" data-day="${c.date}"><span class="dayNum">${Number(c.date.slice(8,10))}</span><span class="barWrap">${ev.map(e=>`<i class="eventBar ${barClass(e,c.date)}">${['start','single'].includes(barClass(e,c.date))?esc(e.title):''}</i>`).join('')}</span></button>`}
  function prep(){const p=state.page.prep||'home';if(p==='gear')return gearPage();if(p==='shop')return shopPage();if(p==='load')return loadPage();if(p==='meal')return mealPage();if(p==='weather')return weatherPage();return shell(`<section class="page">${back('ホーム')}${titleBox('準備','出発前に見るのはこれだけ。')}<section class="grid4"><button class="card" data-prep-page="shop"><b>買うもの</b><small>${state.shopping.filter(s=>!s.done).length}件残り</small></button><button class="card" data-prep-page="load"><b>持っていくもの</b><small>今回の積込チェック</small></button><button class="card" data-prep-page="meal"><b>ごはん</b><small>料理と材料</small></button><button class="card" data-go="routeplan"><b>ルート</b><small>地図・寄り道</small></button><button class="card" data-prep-page="weather"><b>天気</b><small>雨・風・暑さ</small></button><button class="card" data-prep-page="gear"><b>ギア</b><small>登録/BOX/修理</small></button></section></section>`)}
  function shopPage(){return shell(`<section class="page">${back('準備')}${titleBox('買うもの','買ったら済みにする。LINEコピーもここ。')}<section class="list">${state.shopping.map(s=>`<button class="row" data-toggle-shop="${s.id}"><span><b>${esc(s.name)}</b><small>${esc(s.qty)}</small></span><em>${s.done?'済':'まだ'}</em></button>`).join('')}</section><button class="btn dark" data-act="copyShop"><b>LINEコピー</b><small>買い物リストをコピー</small></button></section>`)}
  function loadPage(){return shell(`<section class="page">${back('準備')}${titleBox('持っていくもの','今回の積込チェック。ギア登録とは別。')}<section class="list">${state.gear.map(g=>`<button class="row" data-toggle-gear="${g.id}"><span><b>${esc(g.name)}</b><small>${esc(g.cat)} / ${esc(g.box)}</small></span><em>${g.status==='loaded'?'積んだ':'まだ'}</em></button>`).join('')}</section></section>`)}
  function mealPage(){return shell(`<section class="page">${back('準備')}${titleBox('ごはん','料理と材料を見る。')}<section class="list">${state.meals.map(m=>`<div class="row"><span><b>${esc(m.name)}</b><small>${esc(m.ingredients.join(' / '))}</small></span><em>${esc(m.slot)}</em></div>`).join('')}</section></section>`)}
  function weatherPage(){return shell(`<section class="page">${back('準備')}${titleBox('天気','雨・風・暑さだけ見る。')}<section class="list">${state.weather.map(w=>`<button class="row" data-toggle-weather="${w.id}"><span><b>${esc(w.label)}</b><small>確認したら済みにする</small></span><em>${w.done?'見た':'まだ'}</em></button>`).join('')}</section></section>`)}
  function gearPage(){return shell(`<section class="page">${back('準備')}${titleBox('ギア','登録・BOX・修理。積込は「持っていくもの」。')}<section class="grid2"><button class="btn main" data-act="newGear"><b>新しく登録</b><small>ギアを足す</small></button><button class="btn" data-act="newBox"><b>BOX</b><small>収納を登録</small></button></section><section class="list">${state.gear.map(g=>`<div class="row"><span><b>${esc(g.name)}</b><small>${esc(g.cat)} / ${esc(g.box)}</small></span><em>${esc(g.qty)}</em></div>`).join('')}</section></section>`)}
  function record(){const p=state.page.record||'home';if(p==='kota')return walkPage('コタ散歩','帰宅');if(p==='campWalk')return walkPage('場内散歩','サイト帰着',true);if(p==='drive')return drivePage();if(p==='site')return sitePage();if(p==='setup')return workPage('設営','設営開始','設営完了');if(p==='withdraw')return workPage('撤収','撤収開始','撤収完了');if(p==='camp')return campPage();return recordHome()}
  function recordHome(){return shell(`<section class="page">${back('ホーム')}${titleBox('記録','移動・散歩・場所を見る画面には地図を出す。')}<section class="grid4"><button class="card" data-record-page="camp"><b>キャンプ</b><small>出発から帰宅まで</small></button><button class="card" data-record-page="drive"><b>ドライブ</b><small>地図あり</small></button><button class="card" data-record-page="kota"><b>コタ散歩</b><small>地図あり</small></button><button class="card" data-record-page="campWalk"><b>場内散歩</b><small>地図あり</small></button><button class="card" data-record-page="site"><b>サイト調査</b><small>地図あり</small></button><button class="card" data-record-page="setup"><b>設営</b><small>地図なし</small></button><button class="card" data-record-page="withdraw"><b>撤収</b><small>地図なし</small></button></section></section>`)}
  function campPage(){const on=state.camp.active;return shell(`<section class="page">${back('記録')}${hero('CAMP',on?'キャンプ中':'キャンプに行く',on?'いま必要なことだけ押す。帰宅したら終わる。':'まず出発する。ルートや準備は出発前に確認。',on?'中':'前')}${on?`<section class="panel"><div class="panelHead"><b>今できること</b><small>必要な操作だけ</small></div><div class="grid2"><button class="btn dark" data-record-page="drive"><b>ドライブ</b><small>Google Mapsと併用</small></button><button class="btn" data-act="photo"><b>写真</b><small>今を残す</small></button><button class="btn" data-act="pin"><b>ピン</b><small>場所だけ残す</small></button><button class="btn dark" data-act="voice"><b>話す</b><small>長押し音声</small></button><button class="btn" data-record-page="setup"><b>設営</b><small>開始・休憩・完了</small></button><button class="btn" data-record-page="kota"><b>コタ散歩</b><small>寄り道散歩もここ</small></button><button class="btn" data-record-page="withdraw"><b>撤収</b><small>乾燥・積込</small></button><button class="btn red" data-safe-end="camp"><b>帰宅した</b><small>長押しで終了</small></button></div></section>`:`<section class="panel"><div class="grid2"><button class="btn main" data-act="startCamp"><b>出発する</b><small>キャンプ開始</small></button><button class="btn" data-go="routeplan"><b>行き先・寄り道</b><small>ルートと買い出し</small></button><button class="btn" data-go="prep"><b>準備を見る</b><small>買うもの・持ち物</small></button><button class="btn" data-go="calendar"><b>予定を見る</b><small>日付確認</small></button></div></section>`}<section class="info warn">終了系は長押し。終了後10秒だけ取り消しできます。</section></section>`)}
  function walkPage(title,endLabel,field=false){const active=state.activeMode===title;return shell(`<section class="page">${back('記録')}${titleBox(title,'出発して、ピン・写真・動画・話す。終わったら帰宅。')}${mapEmbed(state.plan.place)}${hero('WALK',active?'散歩中':'まだ出発していない','細かい分類はしない。残すのは場所と写真と声だけ。',active?'中':'前')}<section class="panel"><div class="grid2"><button class="btn main" data-start-mode="${title}"><b>出発</b><small>散歩開始</small></button><button class="btn" data-act="pin"><b>ピン</b><small>場所を残す</small></button><button class="btn" data-act="photo"><b>写真</b><small>写真+位置</small></button><button class="btn" data-act="video"><b>動画</b><small>動画+位置</small></button><button class="btn dark" data-act="voice"><b>話す</b><small>長押し文字起こし</small></button><button class="btn red" data-safe-end="mode" data-mode="${title}"><b>${esc(endLabel)}</b><small>長押しで終了</small></button></div></section><section class="info">地図あり。通常のコタ散歩はカレンダーに入れない。</section></section>`)}
  function drivePage(){return shell(`<section class="page">${back('記録')}${titleBox('ドライブ','Google Mapsはナビ。OUTBASEは停車中のピンと話すだけ。')}${mapEmbed(state.plan.place)}${hero('DRIVE','地図はGoogle Maps。','OUTBASEは記録係。停車中にピンか話すだけでいい。','画面分割')}<section class="panel"><div class="grid2"><button class="btn main" data-start-mode="ドライブ"><b>出発</b><small>ドライブ開始</small></button><button class="btn dark" data-act="openMap"><b>Google Maps</b><small>ナビを開く</small></button><button class="btn" data-act="pin"><b>ピン</b><small>停車中に押す</small></button><button class="btn dark" data-act="voice"><b>話す</b><small>長押し音声メモ</small></button><button class="btn" data-go="routeplan"><b>寄り道</b><small>トイレ/コンビニ/スーパー</small></button><button class="btn red" data-safe-end="mode" data-mode="ドライブ"><b>到着</b><small>長押しで終了</small></button></div></section></section>`)}
  function sitePage(){return shell(`<section class="page">${back('記録')}${titleBox('サイト調査','サイトMAP、気になる場所、設備をピンで残す。')}${mapEmbed(state.plan.place)}<section class="panel"><div class="grid2"><button class="btn main" data-start-mode="サイト調査"><b>調査開始</b><small>開始</small></button><button class="btn" data-act="pin"><b>ピン</b><small>場所を残す</small></button><button class="btn" data-act="photo"><b>写真</b><small>サイト写真</small></button><button class="btn dark" data-act="voice"><b>話す</b><small>長押しメモ</small></button><button class="btn red" data-safe-end="mode" data-mode="サイト調査"><b>終了</b><small>長押しで終了</small></button></div></section></section>`)}
  function workPage(title,start,end){return shell(`<section class="page">${back('記録')}${titleBox(title,'細かく書かず、写真か声で残す。')}<section class="info">この画面は通常地図なし。必要な時だけピンを残す。</section>${hero('WORK',state.activeMode===title?`${title}中`:'まだ始めていない','時間だけでも残れば次回に使える。')}<section class="panel"><div class="grid2"><button class="btn main" data-start-mode="${title}"><b>${esc(start)}</b><small>開始</small></button><button class="btn" data-act="pause"><b>休憩</b><small>一時停止</small></button><button class="btn" data-act="resume"><b>再開</b><small>続き</small></button><button class="btn" data-act="photo"><b>写真</b><small>状況を残す</small></button><button class="btn dark" data-act="voice"><b>話す</b><small>長押し音声</small></button><button class="btn red" data-safe-end="mode" data-mode="${title}"><b>${esc(end)}</b><small>長押しで終了</small></button></div></section></section>`)}
  function routePlan(){return shell(`<section class="page">${back('ホーム')}${titleBox('行き先と寄り道','チェックインに合わせて、トイレ・コンビニ・スーパー・観光を決める。')}${mapEmbed(state.plan.place)}<section class="grid4"><button class="card" data-map="camp"><b>キャンプ場へ</b><small>ルート検索</small></button><button class="card" data-map="toilet"><b>トイレ休憩</b><small>途中で探す</small></button><button class="card" data-map="convenience"><b>コンビニ</b><small>寄り道</small></button><button class="card" data-map="supermarket"><b>スーパー</b><small>買い出し</small></button><button class="card" data-map="sightseeing"><b>観光</b><small>周辺候補</small></button><button class="card" data-map="gas"><b>給油</b><small>ガソリン</small></button></section><button class="btn dark" data-act="saveRoute"><b>この計画を保存</b><small>候補として残す</small></button></section>`)}
  function discover(){return shell(`<section class="page">${back('ホーム')}${titleBox('探す','自分の中を探すか、外を探すか。')}<input class="input" id="q" value="${esc(state.query)}" placeholder="千葉 キャンプ場 など"><section class="grid2"><button class="btn" data-search="outbase"><b>OUTBASE内</b><small>自分の記録・ギア・料理・ピン</small></button><button class="btn" data-search="web"><b>Web</b><small>普通にWeb検索</small></button><button class="btn" data-search="maps"><b>地図</b><small>Google Mapsで場所/経路</small></button><button class="btn" data-search="napp"><b>なっぷ</b><small>キャンプ場検索</small></button></section><button class="btn main" data-act="saveCandidate"><b>候補に保存</b><small>見つけたURLをOUTBASEに残す</small></button></section>`)}
  function memory(){const p=state.page.memory||'home';if(p==='detail')return history();return shell(`<section class="page">${back('ホーム')}${titleBox('思い出','まず履歴を見る。レビューはあとでいい。')}<section class="grid4"><button class="card" data-memory-page="detail"><b>今回のキャンプ</b><small>出発から帰宅まで</small></button><button class="card" data-memory-page="detail"><b>コタ散歩</b><small>ルート・ピン・写真</small></button><button class="card" data-memory-page="detail"><b>ドライブ</b><small>ルート・ピン・音声</small></button><button class="card" data-memory-page="detail"><b>写真・動画</b><small>記録メディア</small></button></section>${titleBox('最近の記録','履歴詳細は上のボタンから見る。')}<section class="list">${state.records.slice().reverse().map(r=>`<div class="row"><span><b>${esc(r.title)}</b><small>${esc(r.time)} / ${esc(r.text)}</small></span><em>${esc(r.kind)}</em></div>`).join('')}</section></section>`)}
  function history(){return shell(`<section class="page">${back('思い出')}${titleBox('詳細履歴','ここでルート・ピン・写真・音声を見る。')}${mapEmbed(state.plan.place)}${hero('HISTORY','キャンプ詳細',`GPS ${state.gps.points}点 / 距離 ${state.gps.distance}km / ピン ${state.pins.length}件 / 記録 ${state.records.length}件`,'詳細')}<section class="list"><div class="row"><span><b>自宅出発</b><small>${state.camp.startedAt?new Date(state.camp.startedAt).toLocaleString('ja-JP'):'未記録'}</small></span><em>開始</em></div><div class="row"><span><b>帰宅到着</b><small>${state.camp.endedAt?new Date(state.camp.endedAt).toLocaleString('ja-JP'):'未記録'}</small></span><em>終了</em></div><div class="row"><span><b>ルート</b><small>GPS ${state.gps.points}点 / 欠測 ${state.gps.gaps}件</small></span><em>地図</em></div><div class="row"><span><b>ピン</b><small>${state.pins.map(p=>p.name).join(' / ')}</small></span><em>${state.pins.length}</em></div></section>${titleBox('タイムライン','押したことが時系列で残る。')}<section class="list">${state.records.map(r=>`<div class="row"><span><b>${esc(r.title)}</b><small>${esc(r.time)} / ${esc(r.text)}</small></span><em>${esc(r.kind)}</em></div>`).join('')}</section></section>`)}
  function drawer(){if(!state.drawer)return '';if(state.drawer==='event')return `<div class="drawer" data-close><div class="drawerCard" data-stop><h2>予定を足す</h2><label>日付<input id="eventDate" type="date" value="${esc(state.selectedDate)}"></label><label>名前<input id="eventTitle" value="キャンプ"></label><div class="drawerActions"><button class="btn" data-act="closeDrawer"><b>閉じる</b></button><button class="btn main" data-act="saveEvent"><b>保存</b></button></div></div></div>`;if(state.drawer==='gear')return `<div class="drawer" data-close><div class="drawerCard" data-stop><h2>ギア登録</h2><label>名前<input id="gearName"></label><label>カテゴリ<input id="gearCat" value="ギア"></label><div class="drawerActions"><button class="btn" data-act="closeDrawer"><b>閉じる</b></button><button class="btn main" data-act="saveGear"><b>保存</b></button></div></div></div>`;return ''}
  let lastDay='',lastTap=0;
  function bind(){/* event delegation handles everything */}
  document.addEventListener('click',e=>{const el=e.target.closest('button,[data-close]'); if(!el)return; if(el.closest('[data-stop]'))return; if(el.dataset.close!==undefined){state.drawer=null;save();return render(false)} if(el.dataset.back!==undefined)return smartBack(); if(el.dataset.go)return go(el.dataset.go); if(el.dataset.recordPage){state.route='record';state.page.record=el.dataset.recordPage;return navPush()} if(el.dataset.prepPage){state.route='prep';state.page.prep=el.dataset.prepPage;return navPush()} if(el.dataset.memoryPage){state.route='memory';state.page.memory=el.dataset.memoryPage;return navPush()} if(el.dataset.day){const d=el.dataset.day,n=Date.now(); if(lastDay===d&&n-lastTap<500){state.selectedDate=d;state.drawer='event'}else{state.selectedDate=d;lastDay=d;lastTap=n}save();return render(false)} if(el.dataset.toggleShop){const s=state.shopping.find(x=>x.id===el.dataset.toggleShop);if(s)s.done=!s.done;save();return render(false)} if(el.dataset.toggleGear){const g=state.gear.find(x=>x.id===el.dataset.toggleGear);if(g)g.status=g.status==='loaded'?'home':'loaded';save();return render(false)} if(el.dataset.toggleWeather){const w=state.weather.find(x=>x.id===el.dataset.toggleWeather);if(w)w.done=!w.done;save();return render(false)} if(el.dataset.startMode){if(!canAct())return;state.activeMode=el.dataset.startMode;state.records.push({id:uid('r'),kind:'開始',title:el.dataset.startMode+'開始',time:nowTime(),text:'記録開始'});save();return render(false)} if(el.dataset.map)return openMap(el.dataset.map); if(el.dataset.search)return search(el.dataset.search); if(el.dataset.act)return act(el.dataset.act,el);});
  document.addEventListener('pointerdown',e=>{const el=e.target.closest('[data-safe-end]'); if(!el)return; el.classList.add('holding'); holdTimer=setTimeout(()=>safeEnd(el),1100)});
  ['pointerup','pointercancel','pointerleave'].forEach(ev=>document.addEventListener(ev,e=>{const el=e.target.closest('[data-safe-end]'); if(el)el.classList.remove('holding'); clearTimeout(holdTimer)}));
  function smartBack(){if(state.route==='prep'&&state.page.prep!=='home'){state.page.prep='home'}else if(state.route==='record'&&state.page.record!=='home'){state.page.record='home'}else if(state.route==='memory'&&state.page.memory!=='home'){state.page.memory='home'}else if(['prep','record','memory','calendar','discover','routeplan'].includes(state.route)){state.route='home'}else{state.route='home'} navPush()}
  function navPush(){save();try{window.history&&window.history.pushState&&window.history.pushState({route:state.route,page:state.page},'',`#${state.route}`)}catch(e){};render(false)}
  function go(r){state.route=r;if(r==='record'&&!state.page.record)state.page.record='home';navPush()}
  window.addEventListener('popstate',()=>smartBack());
  function act(a){if(!canAct()&&!['undo','closeDrawer'].includes(a))return;if(a==='prevMonth'||a==='nextMonth'){const [y,m]=state.currentMonth.split('-').map(Number),d=new Date(y,m-1+(a==='nextMonth'?1:-1),1);state.currentMonth=`${d.getFullYear()}-${pad(d.getMonth()+1)}`;save();return render(false)}if(a==='today'){state.selectedDate=today();state.currentMonth=today().slice(0,7);save();return render(false)}if(a==='addEvent'){state.drawer='event';save();return render(false)}if(a==='saveEvent'){const d=document.getElementById('eventDate').value,t=document.getElementById('eventTitle').value||'予定';state.events.push({id:uid('e'),title:t,type:'normal',start:d,end:d});state.drawer=null;save();return render(false)}if(a==='newGear'){state.drawer='gear';save();return render(false)}if(a==='saveGear'){state.gear.unshift({id:uid('g'),name:document.getElementById('gearName').value||'新しいギア',cat:document.getElementById('gearCat').value||'ギア',box:'home',qty:1,status:'home'});state.drawer=null;save();return render(false)}if(a==='closeDrawer'){state.drawer=null;save();return render(false)}if(a==='startCamp'){state.camp.active=true;state.camp.startedAt=new Date().toISOString();state.records.push({id:uid('r'),kind:'開始',title:'自宅出発',time:nowTime(),text:'キャンプ開始'});save();return render(false)}if(['photo','video','pin','voice'].includes(a)){if(a==='pin')state.pins.push({id:uid('p'),name:'ピン '+nowTime(),kind:'場所',time:nowTime()});state.records.push({id:uid('r'),kind:a==='photo'?'写真':a==='video'?'動画':a==='pin'?'ピン':'音声',title:a==='photo'?'写真':a==='video'?'動画':a==='pin'?'ピン追加':'音声メモ',time:nowTime(),text:'位置付き記録'});save();return toast('記録した')}if(a==='openMap')return openMap('camp');if(a==='saveRoute')return toast('行程を保存');if(a==='copyShop')return toast('コピーした');if(a==='saveCandidate')return toast('候補に保存');if(a==='newBox')return toast('BOX登録は次で拡張');if(a==='pause'||a==='resume')return toast(a==='pause'?'休憩':'再開');if(a==='undo')return runUndo()}
  function safeEnd(el){if(!confirm('終了しますか？'))return; const type=el.dataset.safeEnd, mode=el.dataset.mode; const before=clone(state); if(type==='camp'){state.camp.active=false;state.camp.endedAt=new Date().toISOString();state.records.push({id:uid('r'),kind:'終了',title:'帰宅到着',time:nowTime(),text:'キャンプ終了'});state.route='memory';state.page.memory='home'}else{state.records.push({id:uid('r'),kind:'終了',title:(mode||state.activeMode||'記録')+'終了',time:nowTime(),text:'記録終了'});state.activeMode=''} state.undo={text:'終了しました',before};save();render(false);setTimeout(()=>{if(state.undo&&state.undo.text==='終了しました'){state.undo=null;save();render(false)}},10000)}
  function runUndo(){if(state.undo?.before){state=state.undo.before;state.undo=null;save();render(false)}}
  function openMap(kind){const q={camp:state.plan.place,toilet:`${state.plan.place} 途中 トイレ`,convenience:`${state.plan.place} 途中 コンビニ`,supermarket:`${state.plan.place} 周辺 スーパー`,sightseeing:`${state.plan.place} 周辺 観光`,gas:`${state.plan.place} 途中 ガソリンスタンド`}[kind]||state.plan.place;window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`,'_blank')}
  function search(kind){const q=state.query||'千葉 キャンプ場';if(kind==='outbase')return toast('OUTBASE内を検索');if(kind==='web')window.open(`https://www.google.com/search?q=${encodeURIComponent(q)}`,'_blank');if(kind==='maps')window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`,'_blank');if(kind==='napp')window.open(`https://www.nap-camp.com/search?keyword=${encodeURIComponent(q)}`,'_blank')}
  function render(keep=true){const sx=scrollX,sy=scrollY;const r=state.route;app.innerHTML=r==='calendar'?calendar():r==='prep'?prep():r==='record'?record():r==='routeplan'?routePlan():r==='discover'?discover():r==='memory'?memory():home();if(keep)setTimeout(()=>scrollTo(sx,sy),0)}
  try{window.history&&window.history.replaceState&&window.history.replaceState({route:state.route,page:state.page},'',`#${state.route}`)}catch(e){};
  render(false);
})();
